 ---
title: "Functional score calculation"
date: "`r Sys.Date()`"
author: Yue (Gary) Zhang, PhD
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = T, message = FALSE) 
```

# Preparation

## Load packages and set variables

```{r Initiate, results='hide'}
## initiate ---------------------------------------------------------
# use the following line to set the library path to /data/zhangy68/R/4.3;
# this path is writtable and used by R in sinteractive mode
# this line is nessacery if running interactive web-based Rstudio
.libPaths('/data/zhangy68/R/4.3')

packages_to_load = c(
  "dplyr",
  "Seurat",
  "patchwork",
  "ggplot2",
  "ggrepel",
  "readxl",
  "future",
  "cowplot",
  "Azimuth",
  "dsb",
  "corrplot",
  "DT",
  "tidyr",
  "ggpubr",
  "scRNAtoolVis",
  "purrr",
  "limma",
  "wesanderson",
  "reshape",
  "edgeR",
  'ggfun',
  'ggrepel',
  'fgsea',
  'circlize',
  'ComplexHeatmap',
  'vegan',
  "immunarch"
)
# Load packages without printing output
invisible(suppressPackageStartupMessages({
  lapply(packages_to_load, library, character.only = TRUE)
}))

# Immcantation required packages
suppressPackageStartupMessages(library(airr))
suppressPackageStartupMessages(library(alakazam))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(dowser))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(scoper))
suppressPackageStartupMessages(library(Seurat))
suppressPackageStartupMessages(library(shazam))

# set variables 
setwd('./')
set.seed('123')
col21 <- rev(c("tomato1","darkblue","turquoise1","lightblue","darkred","mediumblue","purple","bisque",
               "greenyellow","yellow","violetred2","darkgreen","darkgoldenrod1","deeppink3","cadetblue4",
               "orchid2","seagreen3","purple4","dodgerblue2","red","gray27"))

```

## Customized functions

```{r function section}
# create a function to generate cluster frequency tables
cluster_freq = function(pbmc,orig.ident,cluster,sex=F){
  freq <- pbmc@meta.data %>%
    group_by(!!sym(orig.ident), !!sym(cluster)) %>%
    summarise(count=n()) %>%
    mutate(relative_frequency = count/sum(count))
  freq$group = ifelse(freq$orig.ident %in% c('HV-1', 'HV-2', 'HV-3'), 'control', 'trisomy8')
  if(sex == T){
    freq$sex = cov$sex[match(freq$orig.ident,cov$sample)]
    freq$group_sex = paste0(freq$group,'_',freq$sex)
    freq$group_sex = factor(freq$group_sex, levels = c('control_F','trisomy8_F','control_M','trisomy8_M'))
  }
  freq$orig.ident = factor(freq$orig.ident, levels = c('HV-1', 'HV-2', 'HV-3','TRIAD-1','TRIAD-3','TRIAD-7', 'TRIAD-2', 'TRIAD-18','TRIAD-4'))
  return(freq)
}
# custom function to plot DE genes between Trisomy and Normal by clusters
plot_de_volcano_scatter = function(df, maxq = 0.1, minLFC=1, showsub = T, sigcol = 'red', sigLowFCcol = 'navyblue', title = 'Trisomy vs Normal') {
  # remove everything after "..." in gene names; bind_rows automatically added these to avoid duplicate rownames.
  df$genes = sub(pattern = '\\.\\.\\.*', replacement = '',x = rownames(df))
  # calculate log10 q value. cap log10 q value at 5 (which is 0.00001 in q val)
  df$p_val_adj_log10 = -log10(df$p_val_adj)
  df$p_val_adj_log10_capped = ifelse(df$p_val_adj_log10 < 5, df$p_val_adj_log10, 5)
  # generate summary statistics to show on caption
  minFDR <- -log10(maxq)
  sigs <- df$p_val_adj_log10 >= minFDR & abs(df$avg_log2FC) >= minLFC
  sigLowFC <- df$p_val_adj_log10 >= minFDR & abs(df$avg_log2FC) < minLFC
  
  cnt_plus <- sum(df$p_val_adj_log10 >= minFDR & df$avg_log2FC >= minLFC)
  cnt_neg <- sum(df$p_val_adj_log10 >= minFDR & df$avg_log2FC <= -minLFC)
  if(showsub) {
    subtitle <- paste0(sum(sigs), " DE genes: ", cnt_plus, " Pos and ", cnt_neg, " Neg",
                       " (FDR<", maxq, ", log2FC>", minLFC, ")")
  } else {
    subtitle <- NULL
  }
  
  p1 = ggplot(df) +
    geom_point(aes(x=avg_log2FC, y=p_val_adj_log10_capped), size=0.5) + 
    geom_point(data=df[sigs,], aes(x=avg_log2FC, y=p_val_adj_log10_capped), size=0.5, col=sigcol) +
    geom_point(data=df[sigLowFC,], aes(x=avg_log2FC, y=p_val_adj_log10_capped), size=0.5, col=sigLowFCcol) +
    ggtitle(title, subtitle=subtitle) + xlab("log2 Fold Change") + ylab("log10 FDR") +
    facet_wrap(.~Celltype_tested,nrow=round(length(unique(df$Celltype_tested))/2))+
    theme(plot.title = element_text(hjust = 0.5), plot.subtitle = element_text(hjust = 0.5)) + 
    geom_vline(xintercept=minLFC, col=sigcol, linetype="dashed", size=0.5) + 
    geom_vline(xintercept=-minLFC, col=sigcol, linetype="dashed", size=0.5) + 
    geom_hline(yintercept=minFDR, col=sigcol, linetype="dashed", size=0.5)
  
  df.s = subset(df, p_val_adj_log10 >minFDR & abs(avg_log2FC) > minLFC)
  df.s = df.s[order(df.s$avg_log2FC, decreasing = TRUE), ]
  df.s$genes = factor(df.s$genes,levels = unique(df.s$genes))
  p2 = ggplot(df.s,mapping = aes(x=genes,y=avg_log2FC,color=p_val_adj_log10_capped)) +
    geom_point() +
    facet_wrap(~ Celltype_tested, scales = 'free') +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    coord_flip() +
    ggtitle(title, subtitle=subtitle) + xlab("log2 Fold Change") + ylab("genes")
  return(list(p1,p2))
}

create_dt <- function(df,caption){
  datatable(df,
            caption = caption,
            extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All")),
                           initComplete = JS(
    "function(settings, json) {",
    "$('caption').css({'font-size': '20px', 'font-family': 'Arial', 'font-weight': 'bold'});",
    "}")))
}

# function to set a column as rownames and remove that column from the df; default is setting the first column as the rowname
setrowname =  function(df,col = 1){
  if (is.numeric(col)) {
    # print('it is a number')
    rownames(df) = df[,col]
    df = df[,-col]
  } else {
    # print('it is a string')
    rownames(df) = df[,which(names(df) %in% c(col))]
    df = df[,-which(names(df) %in% c(col))]
  }
  return(df)
} 

# function to get colors from a palatte
getcol = function(group,pal = "Darjeeling1",shift_col_palatte=0){
  groupcol = as.numeric(factor(group))
  groupcol = wes_palette(pal)[groupcol+shift_col_palatte]
  return(groupcol)
}


# Volcano plot
plot_de_volcano_scatter3 = function(df, maxq = 0.1, minLFC=1, showsub = T, sigcol = 'red', sigLowFCcol = 'navyblue', title = 'Volcano plot',
                                    axislim,leftarrowlim,rightarrowlim) {
  # calculate log10 q value. 
  df$qval_log10 = -log10(df$`adj.P.Val`)
  # generate summary statistics to show on caption
  minFDR <- -log10(maxq)
  sigs <- df$qval_log10 >= minFDR & abs(df$logFC) >= minLFC
  sigLowFC <- df$qval_log10 >= minFDR & abs(df$logFC) < minLFC
  
  cnt_plus <- sum(df$qval_log10 >= minFDR & df$logFC >= minLFC)
  cnt_neg <- sum(df$qval_log10 >= minFDR & df$logFC <= -minLFC)
  if(showsub) {
    subtitle <- paste0(sum(sigs), " DEGs: ", cnt_plus, " + and ", cnt_neg, " -",
                       " (q<", maxq, ", log2FC>", minLFC, ")")
  } else {
    subtitle <- NULL
  }
  
  p1 = ggplot(df) +
    geom_point(aes(x=logFC, y=qval_log10, color = logFC, size = qval_log10)) + 
    geom_point(data =  df %>%
                 subset(qval_log10 >= minFDR) %>%
                 dplyr::arrange(desc(logFC)) %>%
                 dplyr::slice(1:5),
               aes(x = logFC, y = qval_log10,
                   # fill = log2FoldChange,
                   size = qval_log10),
               shape = 21, show.legend = F, color = "#000000") +
    geom_text_repel(data =  df %>%
                      subset(qval_log10 >= minFDR) %>%
                      dplyr::arrange(desc(logFC)) %>%
                      dplyr::slice(1:5),
                    aes(x = logFC, y = qval_log10,label = geneID),
                    box.padding = 0.5,
                    nudge_x = 0.5,
                    nudge_y = 0.2,
                    segment.curvature = -0.1,
                    segment.ncp = 3,
                    # segment.angle = 10,
                    direction = "y", 
                    hjust = "left"
    ) + 
    geom_point(data =  df %>%
                 subset(qval_log10 >= minFDR) %>%
                 dplyr::arrange(logFC) %>%
                 dplyr::slice(1:5),
               aes(x = logFC, y = qval_log10,
                   # fill = log2FoldChange,
                   size = qval_log10),
               shape = 21, show.legend = F, color = "#000000") +
    geom_text_repel(data =  df %>%
                      subset(qval_log10 >= minFDR) %>%
                      dplyr::arrange(logFC) %>%
                      dplyr::slice(1:5),
                    aes(x = logFC, y = qval_log10,label = geneID),
                    box.padding = 0.5,
                    nudge_x = 0.5,
                    nudge_y = 0.2,
                    segment.curvature = -0.1,
                    segment.ncp = 3,
                    # segment.angle = 10,
                    direction = "y", 
                    hjust = "right"
    ) + 
    scale_color_gradientn(colours = c("#3288bd", "#66c2a5","#ffffbf", "#f46d43", "#9e0142"),
                          values = seq(0, 1, 0.2)) +
    scale_fill_gradientn(colours = c("#3288bd", "#66c2a5","#ffffbf", "#f46d43", "#9e0142"),
                         values = seq(0, 1, 0.2)) +
    ggtitle(title, subtitle=subtitle) + xlab("log2 FC") + ylab("-log10 q value") +
    labs(color = 'log2 FC', size = '-log10 q') +
    theme(panel.grid = element_blank(),
          legend.background = element_roundrect(color = "#808080", linetype = 1),
          axis.text = element_text(size = 13, color = "#000000"),
          axis.title = element_text(size = 15),
          plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5)) + 
    geom_vline(xintercept=minLFC, linetype=2) + 
    geom_vline(xintercept=-minLFC, linetype=2) + 
    geom_hline(yintercept=minFDR, linetype=4) +
    coord_cartesian(clip = "off") + 
    annotation_custom(
      grob = grid::segmentsGrob(
        y0 = unit(-10, "pt"),
        y1 = unit(-10, "pt"),
        arrow = arrow(angle = 45, length = unit(.2, "cm"), ends = "first"),
        gp = grid::gpar(lwd = 3, col = "#74add1")
      ), 
      xmin = leftarrowlim[1], 
      xmax = leftarrowlim[2],
      ymin = leftarrowlim[3],
      ymax = leftarrowlim[4]
    ) +
    annotation_custom(
      grob = grid::textGrob(
        label = "Down",
        gp = grid::gpar(col = "#74add1")
      ),
      xmin = leftarrowlim[1], 
      xmax = leftarrowlim[2],
      ymin = leftarrowlim[3],
      ymax = leftarrowlim[4]
    ) +
    annotation_custom(
      grob = grid::segmentsGrob(
        y0 = unit(-10, "pt"),
        y1 = unit(-10, "pt"),
        arrow = arrow(angle = 45, length = unit(.2, "cm"), ends = "last"),
        gp = grid::gpar(lwd = 3, col = "#d73027")
      ), 
      xmin = rightarrowlim[1], 
      xmax = rightarrowlim[2],
      ymin = rightarrowlim[3],
      ymax = rightarrowlim[4]
    ) +
    annotation_custom(
      grob = grid::textGrob(
        label = "Up",
        gp = grid::gpar(col = "#d73027")
      ),
      xmin = rightarrowlim[1], 
      xmax = rightarrowlim[2],
      ymin = rightarrowlim[3],
      ymax = rightarrowlim[4]
    ) 
  if (length(axislim) == 4) {
    p1 = p1 + xlim(axislim[1], axislim[2]) + ylim(axislim[3], axislim[4])
  }
  return(p1)
}

# calculate functional scores
get_functional_scores = function(so,
                                 GEXmatrix,
                                 fl = NULL,
                                 module=NULL){
  # select genes corresponding to the query module
  category = fl[[module]]
  # extract normalized gene expression data
  data = GEXmatrix
  # find existed markers under the query module
  category.shared = intersect(category,rownames(data))
  # find markers not existed in the dataset under the module
  category.missing = setdiff(category,rownames(data))
  # extract normalized expression of genes of interest
  df <-
    data %>%
    t() %>%
    as.data.frame() %>%
    select(category.shared)
  # get averages for genes of interest
  df$avg_genes = rowMeans(df)
  if (all(rownames(so@meta.data) == rownames(df))){
    so@meta.data[[paste0('functional_score_of_',module)]] = df$avg_genes
    return(list(so,category.shared,category.missing,length(category.shared)/length(category)))
  } else {
    return('cell barcodes do not match')
  }
}

```

## Load seurat object


```{r load pbmc, eval=T}
pbmc = readRDS('srt.obj.merged.clusterCuratedRefined.classifiedSet.myeloidInfoAdded.metadataIdentifierAdded.RDS')
pbmc.copy1 <- pbmc
#pbmc.copy1 -> pbmc
pbmc.metadata = pbmc@meta.data
pbmc.mld2 = readRDS('pbmc.mld2.SexAgeAdded.RDS')
pbmc.mld2.copy1 <- pbmc.mld2
#pbmc.mld2.copy1 -> pbmc.mld2
```


```{r fs pw selection}
# (this step takes a long time, so do it once for all following iterations)
geneSet.kegg = gmtPathways('c2.cp.kegg_medicus.v2023.2.Hs.symbols.gmt')
geneSet.reactome =gmtPathways('c2.cp.reactome.v2023.2.Hs.symbols.gmt') 
geneSet.go = gmtPathways('c5.go.bp.v2023.2.Hs.symbols.gmt')
geneSet.hallmark = gmtPathways('h.all.v2023.2.Hs.symbols.gmt')
geneSet.merged4 = c(geneSet.kegg,geneSet.reactome,geneSet.go,geneSet.hallmark)

pw = c('HALLMARK_INTERFERON_GAMMA_RESPONSE',
'HALLMARK_Interferon alpha response',
'GOBP_Response to type II INTERFERON',
'GOBP_Response to type I INTERFERON',
'HALLMARK_TNFA signaling via NFKB',
'HALLMARK_IL6_JAK_STAT3_Signaling',
'HALLMARK_Apoptosis',
"GOBP_RESPONSE_TO_TUMOR_NECROSIS_FACTOR",
'GOBP_Monocyte chemotaxis',
'REACTOME_Translation',
  "GOBP_RESPONSE_TO_INTERLEUKIN_1",
  "GOBP_POSITIVE_REGULATION_OF_INTERLEUKIN_1_BETA_PRODUCTION",
  "GOBP_INTERLEUKIN_1_MEDIATED_SIGNALING_PATHWAY",
  "GOBP_INTERLEUKIN_1_PRODUCTION",
  "GOBP_CELLULAR_RESPONSE_TO_INTERLEUKIN_1",
  "REACTOME_INTERLEUKIN_1_SIGNALING"
)

# Capitalize all letters and replace spaces with underscores
pw <- toupper(gsub(" ", "_", pw))
# check if everything matched
setdiff(pw,names(geneSet.merged4))
```

# Calculation on the full dataset

```{r fs calc}
# get normalized gene expression data (this step takes a long time, so do it once for all following iterations)
pbmc.RNA.data = as.data.frame(pbmc@assays$RNA@data)
# create a empty dataframe to store the genes used to calculate functional scores
# Create an empty dataframe
fs_genes <- data.frame(
  genes_used = character(),  # the genes within a module that also are also present in the data
  genes_missing = character(), # the genes within a module that are missing from the data
  fraction_of_present_genes = numeric(),
  stringsAsFactors = FALSE
)
# calculate functional scores for the modules of interest

for (module in pw) {
  print(paste0("calculating functional score for module: ",module))
  results = get_functional_scores(pbmc,pbmc.RNA.data,geneSet.merged4,module)
  pbmc = results[[1]]
  fs_genes[module, "genes_used"] <- paste(results[[2]], collapse = "; ")
  fs_genes[module, "genes_missing"] <- paste(results[[3]], collapse = "; ")
  fs_genes[module, "fraction_of_present_genes"] <- results[[4]]
  print(paste0("The percentage of genes within the module that are present in the data are: ", results[[4]]))
}
saveRDS(fs_genes,"functional_score_genes_summary.session30.rds")
saveRDS(pbmc,"srt.obj.merged.clusterCuratedRefined.classifiedSet.myeloidInfoAdded.metadataIdentifierAdded.FuncSAdded.RDS")
```

# Calculation on the myeloid subset

```{r fs calc mld}
# get normalized gene expression data (this step takes a long time, so do it once for all following iterations)
pbmc.mld2.RNA.data = as.data.frame(pbmc.mld2@assays$RNA@data)
# create a empty dataframe to store the genes used to calculate functional scores
# Create an empty dataframe
fs_genes.mld2 <- data.frame(
  genes_used = character(),  # the genes within a module that also are also present in the data
  genes_missing = character(), # the genes within a module that are missing from the data
  fraction_of_present_genes = numeric(),
  stringsAsFactors = FALSE
)
# calculate functional scores for the modules of interest

for (module in pw) {
  print(paste0("calculating functional score for module: ",module))
  results = get_functional_scores(pbmc.mld2,pbmc.mld2.RNA.data,geneSet.merged4,module)
  pbmc.mld2 = results[[1]]
  fs_genes.mld2[module, "genes_used"] <- paste(results[[2]], collapse = "; ")
  fs_genes.mld2[module, "genes_missing"] <- paste(results[[3]], collapse = "; ")
  fs_genes.mld2[module, "fraction_of_present_genes"] <- results[[4]]
  print(paste0("The percentage of genes within the module that are present in the data are: ", results[[4]]))
}
saveRDS(fs_genes.mld2,"functional_score_genes_summary.mld2.session30.rds")
saveRDS(pbmc.mld2,"pbmc.mld2.SexAgeAdded.FuncSAdded.RDS")
```

